<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CakesMenu.Designer.cs" />
    <Compile Remove="Cart.cs" />
    <Compile Remove="Cart.Designer.cs" />
    <Compile Remove="Coffeemenu.Designer.cs" />
    <Compile Remove="Details.cs" />
    <Compile Remove="Details.Designer.cs" />
    <Compile Remove="DineTakeout.cs" />
    <Compile Remove="DineTakeout.Designer.cs" />
    <Compile Remove="Home.cs" />
    <Compile Remove="Home.Designer.cs" />
    <Compile Remove="Homemenu.cs" />
    <Compile Remove="Homemenu.Designer.cs" />
    <Compile Remove="Intro.cs" />
    <Compile Remove="Intro.Designer.cs" />
    <Compile Remove="OrderSuccessForm..cs" />
    <Compile Remove="OrderSuccessForm.Designer.cs" />
    <Compile Remove="Pasteries.cs" />
    <Compile Remove="Pasteries.Designer.cs" />
    <Compile Remove="Pop_up.cs" />
    <Compile Remove="Pop_up.Designer.cs" />
    <Compile Remove="YesNo.cs" />
    <Compile Remove="YesNo.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Cart.resx" />
    <EmbeddedResource Remove="Coffeemenu.resx" />
    <EmbeddedResource Remove="Details.resx" />
    <EmbeddedResource Remove="DineTakeout.resx" />
    <EmbeddedResource Remove="Home.resx" />
    <EmbeddedResource Remove="Homemenu.resx" />
    <EmbeddedResource Remove="Intro.resx" />
    <EmbeddedResource Remove="OrderSuccessForm..resx" />
    <EmbeddedResource Remove="Pasteries.resx" />
    <EmbeddedResource Remove="Pop_up.resx" />
    <EmbeddedResource Remove="YesNo.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Products\Drinks\how-to-make-chocolate-milk-7.webp" />
    <None Remove="Resources\Products\Drinks\placeholder.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="Tulpep.NotificationWindow" Version="1.1.38" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>